resources:
  - externalsecret.yaml
  - deployment.yaml

images:
  - name: govee2mqtt
    newName: ghcr.io/wez/govee2mqtt
    newTag: 2026.03.25-ab9deb66
    digest: sha256:a9d9fe330574d16be5a68175f2572615f9e55385695ab40652cc388076a07643

labels:
  - includeTemplates: true
    pairs:
      app.kubernetes.io/name: govee2mqtt
  - includeSelectors: true
    pairs:
      app: govee2mqtt
      app.kubernetes.io/component: mqtt_gateway

generatorOptions:
  annotations:
    argocd.argoproj.io/sync-options: Prune=true

configMapGenerator:
  - envs:
      - gv2mqtt.env
    name: gv2mqtt-env
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
