resources:
  - pvc.yaml
  - deployment.yaml
  - service.yaml
  - route.yaml
  - monitoring.yaml

labels:
  - includeTemplates: true
    pairs:
      app.kubernetes.io/component: manager
      app.kubernetes.io/name: overseerr
  - includeSelectors: true
    includeTemplates: true
    pairs:
      app: overseerr

images:
  - name: overseerr
    newName: ghcr.io/sct/overseerr
    newTag: 1.35.0
    digest: sha256:6197516c9d7b58ccf113455e32aafb94df5d91995fe50e8c2cae6ba6c7c7b7de
  - name: overseerr_exporter
    newName: ghcr.io/willfantom/overseerr-exporter
    digest: sha256:80bafb994cbeb3a418d54b8d72ac0f25fb6b0202d272e199a1161cc95a4e90f5

generatorOptions:
  annotations:
    argocd.argoproj.io/sync-options: Prune=true
  immutable: true

configMapGenerator:
  - envs:
      - backup-conf.env
    name: overseerr-backup
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
