{
 "title": "ArgoCD",
 "description": "ArgoCD Dashboard",
 "time": { "from": "now-1h", "to": "now" },
 "templating": {
  "list": [
   { "name": "datasource", "query": "prometheus" }
  ]
 },
 "panels": [
  { "title": "Overview", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "type": "text",
   "gridPos": { "h": 4, "w": 2, "x": 0, "y": 1 },
   "options": {
    "content": "![argoimage](https://avatars1.githubusercontent.com/u/30269780?s=110&v=4)"
   }
  },
  {
   "title": "Uptime",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 2, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "dtdhms" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "time() - max(process_start_time_seconds{job=\"openshift-gitops-server-metrics\"})"
    }
   ]
  },
  {
   "title": "Applications",
   "type": "stat",
   "gridPos": { "h": 7, "w": 4, "x": 8, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count(sum(argocd_app_info) by (name))"
    }
   ]
  },
  {
   "title": "Repositories",
   "type": "stat",
   "gridPos": { "h": 7, "w": 4, "x": 12, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count(count by (repo) (argocd_app_info{}))"
    }
   ]
  },
  {
   "title": "Projects",
   "type": "piechart",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count(sum(argocd_app_info) by (name,project)) by (project)",
     "legendFormat": "{{project}}"
    }
   ]
  },
  {
   "title": "Application Status",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 8 },
   "collapsed": true,
   "panels": [
    {
     "title": "Health Status",
     "type": "timeseries",
     "gridPos": { "h": 6, "w": 12, "x": 0, "y": 9 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "count(sum(argocd_app_info) by (health_status, name)) by (health_status)",
       "legendFormat": "{{health_status}}"
      }
     ]
    },
    {
     "title": "Sync Status",
     "type": "timeseries",
     "gridPos": { "h": 6, "w": 12, "x": 12, "y": 9 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "sum(count(argocd_app_info) by (sync_status, name)) by (sync_status)",
       "legendFormat": "{{sync_status}}"
      }
     ]
    }
   ]
  },
  {
   "title": "Sync Stats",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 9 },
   "collapsed": true,
   "panels": [
    {
     "title": "Sync Activity",
     "type": "timeseries",
     "gridPos": { "h": 6, "w": 24, "x": 0, "y": 10 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "sum(round(increase(argocd_app_sync_total[1h]))) by (project)",
       "legendFormat": "{{project}}"
      }
     ]
    },
    {
     "title": "Sync Failures",
     "type": "timeseries",
     "gridPos": { "h": 5, "w": 24, "x": 0, "y": 16 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "expr": "sum(round(increase(argocd_app_sync_total{phase=~\"Error|Failed\",}[1h]))) by (project, phase)",
       "legendFormat": "{{phase}}: {{project}}"
      }
     ]
    }
   ]
  },
  {
   "title": "Controller Stats",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 10 },
   "collapsed": true,
   "panels": [
    {
     "title": "Reconciliation Activity",
     "type": "timeseries",
     "gridPos": { "h": 6, "w": 24, "x": 0, "y": 11 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "sum(increase(argocd_app_reconcile_count[1h])) by (project)",
       "legendFormat": "{{project}}"
      }
     ]
    },
    {
     "title": "Reconciliation Performance",
     "type": "heatmap",
     "gridPos": { "h": 7, "w": 24, "x": 0, "y": 17 },
     "targets": [
      {
       "expr": "sum(increase(argocd_app_reconcile_bucket{}[1h])) by (le)",
       "legendFormat": "{{le}}"
      }
     ]
    },
    {
     "title": "K8s API Activity",
     "type": "timeseries",
     "gridPos": { "h": 6, "w": 24, "x": 0, "y": 24 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "sum(increase(argocd_app_k8s_request_total[1h])) by (verb, resource_kind)",
       "legendFormat": "{{verb}} {{resource_kind}}"
      }
     ]
    },
    {
     "title": "Workqueue Depth",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 12, "x": 0, "y": 30 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "sum(workqueue_depth{namespace=\"openshift-gitops\"}) by (name)",
       "legendFormat": "{{name}}"
      }
     ]
    },
    {
     "title": "Pending kubectl run",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 12, "x": 12, "y": 30 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "sum(argocd_kubectl_exec_pending{}) by (command)",
       "legendFormat": "{{command}}"
      }
     ]
    }
   ]
  },
  {
   "title": "Controller Telemetry",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 11 },
   "collapsed": true,
   "panels": [
    {
     "title": "Memory Usage",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 24, "x": 0, "y": 12 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "targets": [
      {
       "expr": "go_memstats_heap_alloc_bytes{job=\"openshift-gitops-metrics\",}",
       "legendFormat": "{{namespace}}"
      }
     ]
    },
    {
     "title": "CPU Usage",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 24, "x": 0, "y": 19 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "expr": "irate(process_cpu_seconds_total{job=\"openshift-gitops-metrics\"}[1m])",
       "legendFormat": "{{namespace}}"
      }
     ]
    },
    {
     "title": "Goroutines",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 24, "x": 0, "y": 26 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "go_goroutines{job=\"openshift-gitops-metrics\",}",
       "legendFormat": "{{namespace}}"
      }
     ]
    }
   ]
  },
  {
   "title": "Cluster Stats",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 12 },
   "collapsed": true,
   "panels": [
    {
     "title": "Resource Objects Count",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 24, "x": 0, "y": 13 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "sum(argocd_cluster_api_resource_objects)",
       "legendFormat": "K8S"
      }
     ]
    },
    {
     "title": "API Resources Count",
     "type": "timeseries",
     "gridPos": { "h": 6, "w": 24, "x": 0, "y": 20 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "  sum(argocd_cluster_api_resources)",
       "legendFormat": "K8S"
      }
     ]
    },
    {
     "title": "Cluster Events Count",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 24, "x": 0, "y": 26 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "sum(increase(argocd_cluster_events_total[1h]))",
       "legendFormat": "K8S"
      }
     ]
    }
   ]
  },
  {
   "title": "Repo Server Stats",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 13 },
   "collapsed": true,
   "panels": [
    {
     "title": "Git Requests (ls-remote)",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 14 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum(increase(argocd_git_request_total{request_type=\"ls-remote\", }[10m])) by (namespace)",
       "legendFormat": "{{namespace}}"
      }
     ]
    },
    {
     "title": "Git Requests (checkout)",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 14 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum(increase(argocd_git_request_total{request_type=\"fetch\", }[10m])) by (namespace)",
       "legendFormat": "{{namespace}}"
      }
     ]
    },
    {
     "title": "Git Fetch Performance",
     "type": "heatmap",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 22 },
     "targets": [
      {
       "expr": "sum(increase(argocd_git_request_duration_seconds_bucket{request_type=\"fetch\", }[1h])) by (le)",
       "legendFormat": "{{le}}"
      }
     ]
    },
    {
     "title": "Git Ls-Remote Performance",
     "type": "heatmap",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 22 },
     "targets": [
      {
       "expr": "sum(increase(argocd_git_request_duration_seconds_bucket{request_type=\"ls-remote\", }[1h])) by (le)",
       "legendFormat": "{{le}}"
      }
     ]
    },
    {
     "title": "Memory Used",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 24, "x": 0, "y": 30 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "targets": [
      {
       "expr": "go_memstats_heap_alloc_bytes{job=\"openshift-gitops-repo-server\",}",
       "legendFormat": "{{pod}}"
      }
     ]
    },
    {
     "title": "Goroutines",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 24, "x": 0, "y": 38 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "go_goroutines{job=\"openshift-gitops-repo-server\",}",
       "legendFormat": "{{pod}}"
      }
     ]
    }
   ]
  },
  {
   "title": "Server Stats",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 14 },
   "collapsed": true,
   "panels": [
    {
     "title": "Memory Used",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 24, "x": 0, "y": 15 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "targets": [
      {
       "expr": "go_memstats_heap_alloc_bytes{job=\"openshift-gitops-server-metrics\",}",
       "legendFormat": "{{container}}"
      }
     ]
    },
    {
     "title": "Goroutines",
     "type": "timeseries",
     "gridPos": { "h": 9, "w": 24, "x": 0, "y": 23 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "go_goroutines{job=\"openshift-gitops-server-metrics\",}",
       "legendFormat": "{{container}}"
      }
     ]
    },
    {
     "title": "GC Time Quantiles",
     "type": "timeseries",
     "gridPos": { "h": 9, "w": 24, "x": 0, "y": 32 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "go_gc_duration_seconds{job=\"openshift-gitops-server-metrics\", quantile=\"1\"}",
       "legendFormat": "{{container}}"
      }
     ]
    },
    { "type": "text", "gridPos": { "h": 2, "w": 24, "x": 0, "y": 41 }, "options": { "content": "#### gRPC Services:" } },
    {
     "title": "ApplicationService Requests",
     "type": "timeseries",
     "gridPos": { "h": 9, "w": 12, "x": 0, "y": 43 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "sum(increase(grpc_server_handled_total{job=\"openshift-gitops-server-metrics\",grpc_service=\"application.ApplicationService\",}[1h])) by (grpc_code, grpc_method)",
       "legendFormat": "{{grpc_code}},{{grpc_method}}"
      }
     ]
    },
    {
     "title": "ClusterService Requests",
     "type": "timeseries",
     "gridPos": { "h": 9, "w": 12, "x": 12, "y": 43 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "sum(increase(grpc_server_handled_total{job=\"openshift-gitops-server-metrics\",grpc_service=\"cluster.ClusterService\",}[1h])) by (grpc_code, grpc_method)",
       "legendFormat": "{{grpc_code}},{{grpc_method}}"
      }
     ]
    },
    {
     "title": "ProjectService Requests",
     "type": "timeseries",
     "gridPos": { "h": 9, "w": 12, "x": 0, "y": 52 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "sum(increase(grpc_server_handled_total{job=\"openshift-gitops-server-metrics\",grpc_service=\"project.ProjectService\",}[1h])) by (grpc_code, grpc_method)",
       "legendFormat": "{{grpc_code}},{{grpc_method}}"
      }
     ]
    },
    {
     "title": "RepositoryService Requests",
     "type": "timeseries",
     "gridPos": { "h": 9, "w": 12, "x": 12, "y": 52 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "sum(increase(grpc_server_handled_total{job=\"openshift-gitops-server-metrics\",grpc_service=\"repository.RepositoryService\",}[1h])) by (grpc_code, grpc_method)",
       "legendFormat": "{{grpc_code}},{{grpc_method}}"
      }
     ]
    },
    {
     "title": "SessionService Requests",
     "type": "timeseries",
     "gridPos": { "h": 9, "w": 12, "x": 0, "y": 61 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "sum(increase(grpc_server_handled_total{job=\"openshift-gitops-server-metrics\",grpc_service=\"session.SessionService\",}[1h])) by (grpc_code, grpc_method)",
       "legendFormat": "{{grpc_code}},{{grpc_method}}"
      }
     ]
    },
    {
     "title": "VersionService Requests",
     "type": "timeseries",
     "gridPos": { "h": 9, "w": 12, "x": 12, "y": 61 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "sum(increase(grpc_server_handled_total{job=\"openshift-gitops-server-metrics\",grpc_service=\"version.VersionService\",}[1h])) by (grpc_code, grpc_method)",
       "legendFormat": "{{grpc_code}},{{grpc_method}}"
      }
     ]
    },
    {
     "title": "AccountService Requests",
     "type": "timeseries",
     "gridPos": { "h": 9, "w": 12, "x": 0, "y": 70 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "sum(increase(grpc_server_handled_total{job=\"openshift-gitops-server-metrics\",grpc_service=\"account.AccountService\",}[1h])) by (grpc_code, grpc_method)",
       "legendFormat": "{{grpc_code}},{{grpc_method}}"
      }
     ]
    },
    {
     "title": "SettingsService Requests",
     "type": "timeseries",
     "gridPos": { "h": 9, "w": 12, "x": 12, "y": 70 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "sum(increase(grpc_server_handled_total{job=\"openshift-gitops-server-metrics\",grpc_service=\"settings.SettingsService\",}[1h])) by (grpc_code, grpc_method)",
       "legendFormat": "{{grpc_code}},{{grpc_method}}"
      }
     ]
    }
   ]
  }
 ]
}