{
 "title": "Redis Exporter",
 "description": "A quickstart to setup the Prometheus Redis Exporter with preconfigured dashboards, alerting rules, and recording rules.",
 "tags": [
  "prometheus",
  "redis"
 ],
 "time": { "from": "now-12h", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "namespace",
    "query": "label_values(redis_up, namespace)"
   },
   { "name": "datasource", "query": "prometheus" }
  ]
 },
 "panels": [
  {
   "title": "Performance",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Commands per second",
   "type": "timeseries",
   "description": "Average taken across instances",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "avg(irate(redis_commands_total{namespace=~\"$namespace\"} [1m])) by (cmd)",
     "legendFormat": "{{cmd}}"
    }
   ]
  },
  {
   "title": "Command latency per second",
   "type": "timeseries",
   "description": "Average taken across instances",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "avg(irate(redis_commands_duration_seconds_total{namespace=~\"$namespace\"}[1m])) by (cmd)\n  /\navg(irate(redis_commands_total{namespace=~\"$namespace\"}[1m])) by (cmd)\n",
     "legendFormat": "{{ cmd }}"
    }
   ]
  },
  {
   "title": "Hit ratio per instance",
   "type": "timeseries",
   "description": "Hit rate shows the percentage of key space lookups that hit a key.",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "avg(irate(redis_keyspace_hits_total{namespace=~\"$namespace\"}[1m]) / (irate(redis_keyspace_misses_total{namespace=~\"$namespace\"}[1m]) + irate(redis_keyspace_hits_total{namespace=~\"$namespace\"}[1m]))) by (namespace, job)",
     "legendFormat": "{{namespace}} - {{job}}"
    },
    { "expr": "1", "legendFormat": "Target hit ratio for cache" }
   ]
  },
  {
   "title": "Memory",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 8 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Total Memory Usage",
   "type": "timeseries",
   "description": "Total taken across instances",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "sum(redis_memory_used_bytes{namespace=~\"$namespace\"})",
     "legendFormat": "Used Memory"
    },
    {
     "expr": "sum(redis_memory_max_bytes{namespace=~\"$namespace\"})",
     "legendFormat": "Configured max memory"
    },
    {
     "expr": "sum(redis_memory_used_rss_bytes{namespace=~\"$namespace\"})",
     "legendFormat": "Used RSS memory"
    }
   ]
  },
  {
   "title": "Memory fragmentation ratio per instance",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "redis_memory_fragmentation_ratio{namespace=~\"$namespace\"}",
     "legendFormat": "{{namespace}} - {{job}}"
    }
   ]
  },
  {
   "title": "Key evictions per second per instance",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "irate(redis_evicted_keys_total{namespace=~\"$namespace\"}[1m])",
     "legendFormat": "{{namespace}} - {{job}}"
    }
   ]
  },
  {
   "title": "Basic activity",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 16 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Connected/Blocked Clients",
   "type": "timeseries",
   "description": "Sum taken across instances",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 17 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(redis_connected_clients{namespace=~\"$namespace\"})",
     "legendFormat": "Connected"
    },
    {
     "expr": "sum(redis_blocked_clients{namespace=~\"$namespace\"})",
     "legendFormat": "Blocked"
    }
   ]
  },
  {
   "title": "Total Items per DB",
   "type": "timeseries",
   "description": "Sum taken across instances",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 17 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "sum (redis_db_keys{namespace=~\"$namespace\"}) by (db)",
     "legendFormat": "{{ db }}"
    }
   ]
  },
  {
   "title": "Expiring vs Not-Expiring Keys",
   "type": "timeseries",
   "description": "Sum taken across instances",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 17 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum (redis_db_keys{namespace=~\"$namespace\"}) - sum (redis_db_keys_expiring{namespace=~\"$namespace\"})",
     "legendFormat": "Not expiring"
    },
    {
     "expr": "sum(redis_db_keys_expiring{namespace=~\"$namespace\"})",
     "legendFormat": "Expiring"
    }
   ]
  },
  {
   "title": "Connected slaves by namespace",
   "type": "timeseries",
   "description": "This metric will only be non-zero if the instance is a master",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 24 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(redis_connected_slaves{namespace=~\"$namespace\"}) by (namespace)",
     "legendFormat": "{{namespace}}"
    }
   ]
  },
  {
   "title": "Time since last master connection",
   "type": "timeseries",
   "description": "This metric is only exported if the instance is a slave.",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 24 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "redis_master_last_io_seconds_ago{namespace=~\"$namespace\"}",
     "legendFormat": "{{namespace}}"
    }
   ]
  }
 ]
}