apiVersion: k8s.cni.cncf.io/v1
kind: NetworkAttachmentDefinition
metadata:
  name: media
  namespace: media
spec:
  config: |-
    {
      "cniVersion": "0.4.0",
      "name": "media",
      "type": "ovn-k8s-cni-overlay",
      "topology": "localnet",
      "vlanID": 6,
      "mtu": 1500,
      "netAttachDefName": "media/media",
      "ipam": {
        "type": "dhcp",
        "provide": [
          {
            "option": "host-name",
            "fromArg": "K8S_POD_NAME"
          },
          {
            "option": "vendor-class-identifier",
            "value": "openshift"
          }
        ],
        "request": [
          {
            "option": "subnet-mask",
            "skipDefault": true 
          }
        ]
      }
    }
