resources:
  - pvc.yaml
  - deployment.yaml
  - service.yaml
  - monitoring.yaml
  - route.yaml

images:
  - name: homeassistant/home-assistant
    newName: ghcr.io/home-assistant/home-assistant
    newTag: 2026.5.4
    digest: sha256:ceb1202133a5a036e8b03e20a10eb113186cc2f871968323c6fc6c3fc4205716
labels:
  - includeTemplates: true
    pairs:
      app.kubernetes.io/name: hass
  - includeSelectors: true
    pairs:
      app: homeassistant
      app.kubernetes.io/component: homeassistant

generatorOptions:
  annotations:
    argocd.argoproj.io/sync-options: Prune=true

configMapGenerator:
  - behavior: create
    envs:
      - backup-conf.env
    name: hass-backup
  - behavior: create
    files:
      - containerenv
    name: hass-containerenv
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
