{
 "title": "Closet Status",
 "time": { "from": "now-2d", "to": "now" },
 "refresh": "1m",
 "panels": [
  { "title": "Router", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Uptime",
   "type": "stat",
   "gridPos": { "h": 5, "w": 4, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "dtdhms" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "(time() - (snmp_value_hrSystemUptime))/ 1000"
    }
   ]
  },
  {
   "title": "Version",
   "type": "stat",
   "gridPos": { "h": 5, "w": 3, "x": 4, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "snmp_value_mtxrFirmwareVersion", "legendFormat": "{{mtxrFirmwareVersion}}" }
   ]
  },
  {
   "title": "CPU",
   "type": "stat",
   "gridPos": { "h": 5, "w": 3, "x": 7, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(snmp_value_hrProcessorLoad{instance=\"router.homelab.csfreak.com\"} != 0) / count(snmp_value_hrProcessorLoad{instance=\"router.homelab.csfreak.com\"} != 0)"
    }
   ]
  },
  {
   "title": "Memory",
   "type": "stat",
   "gridPos": { "h": 5, "w": 3, "x": 10, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "snmp_value_hrStorageUsed{instance=\"router.homelab.csfreak.com\",hrStorageDescr=\"main memory\"} / snmp_value_hrStorageSize{instance=\"router.homelab.csfreak.com\",hrStorageDescr=\"main memory\"}"
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 5, "w": 7, "x": 13, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "fahrenheit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "(snmp_value_mtxrGaugeValue + on (mtxrGaugeIndex) group_right(mtxrGuageName) snmp_value_mtxrGaugeName{mtxrGaugeName=~\".*temperature\"} - 1) * 9 / 5 + 32",
     "legendFormat": "{{mtxrGaugeName}}"
    }
   ]
  },
  {
   "title": "Internet Bandwidth",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "bps" } },
   "targets": [
    {
     "expr": "rate(snmp_value_ifHCInOctets{ifName=\"NetINETv5\"}[$__rate_interval]) * 8",
     "legendFormat": "Download"
    },
    {
     "expr": "rate(snmp_value_ifHCOutOctets{ifName=\"NetINETv5\"}[$__rate_interval]) * 8",
     "legendFormat": "Upload"
    }
   ]
  },
  {
   "title": "Average Bandwidth",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "bps" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "rate(snmp_value_ifHCInOctets{ifName=\"NetINETv5\"}[1h]) * 8",
     "legendFormat": "Download"
    },
    {
     "expr": "rate(snmp_value_ifHCOutOctets{ifName=\"NetINETv5\"}[1h]) * 8",
     "legendFormat": "Upload"
    }
   ]
  }
 ]
}